# Generated by Django 3.2.6 on 2022-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220802_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('case_type', models.CharField(max_length=40)),
            ],
        ),
    ]
