# Generated by Django 3.2.6 on 2022-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_todo_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='field_name',
            field=models.FileField(default=False, max_length=254, upload_to=None),
        ),
    ]
