# Generated by Django 3.2.6 on 2022-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_todo_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='description',
        ),
        migrations.AddField(
            model_name='case',
            name='case_description',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
