# Generated by Django 3.2.6 on 2022-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220804_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=50)),
                ('sec_def', models.TextField(default=True, max_length=100)),
            ],
        ),
    ]
