# Generated by Django 3.2.6 on 2022-08-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_uploadcasefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='hash_key',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='case',
            name='transaction_id',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(default=True, max_length=40),
        ),
    ]
