# Generated by Django 3.2.6 on 2022-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_uploadcasefile_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcasefile',
            name='file_descripion',
            field=models.TextField(default='sample'),
        ),
        migrations.AlterField(
            model_name='uploadcasefile',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
