# Generated by Django 4.0.5 on 2022-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220813_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcasefile',
            name='file_descripion',
        ),
        migrations.AlterField(
            model_name='uploadcasefile',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
