# Generated by Django 4.0.5 on 2022-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_uploadcasefile_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcasefile',
            name='uploadfile_description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='uploadcasefile',
            name='uploadfile_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadcasefile',
            name='uploadfile',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
