# -*- coding: utf-8 -*-
"""indicTrans_python_interface.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/AI4Bharat/indicTrans/blob/main/indicTrans_python_interface.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# clone the repo for running evaluation
# %cd indicTrans
# clone requirements repositories

"""# New section"""

# Commented out IPython magic to ensure Python compatibility.
# Install the necessary libraries
#!pip install sacremoses pandas mock sacrebleu tensorboardX pyarrow indic-nlp-library
#! pip install mosestokenizer subword-nmt
# Install fairseq from source
#!git clone https://github.com/pytorch/fairseq.git
# %cd fairseq
# !git checkout da9eaba12d82b9bfc1442f0e2c6fc1b895f4d35d
#!pip install ./
#! pip install xformers
# %cd ..

# add fairseq folder to python path
import os
os.environ['PYTHONPATH'] += ":/content/fairseq/"
# sanity check to see if fairseq is installed
from fairseq import checkpoint_utils, distributed_utils, options, tasks, utils


from indicTrans.inference.engine import Model

en2indic_model = Model(expdir='../en-indic')

ta_sents = ['He seems to know us.',
            "We will follow you or continue to follow you",
            'If you develop these symptoms in someone close to you, staying at home can help prevent the spread of Corona virus infection.']


en2indic_model.batch_translate(ta_sents, 'en', 'ta')

hi_paragraph = """The pandemic has caused global social and economic disruption. This has led to the worlds largest recession since the Great Depression. This led to the postponement or cancellation of sporting, religious, political and cultural events. Due to this fear, there was a shortage of supply as most of the people purchased the items like masks, sanitizers etc."""

en2indic_model.translate_paragraph(hi_paragraph, 'en', 'hi')

